try{
    const a = 10
    a = 15
}
catch(error)
{
    console.log("Error")
}
